server:
  port: 8080

logging:
  level:
    root: INFO
    DEBUGLOGGER: DEBUG
    org:
      springframework:
        web: INFO
        filter:
          CommonsRequestLoggingFilter: DEBUG
      hibernate: ERROR

